export const CHAIN_TO_COINGECKO_ID: { [key: string]: string } = {
  'osmosis': 'osmosis',
  'cosmoshub': 'cosmos',
  'celestia': 'celestia',
  'akash': 'akash-network',
  'regen': 'regen',
  'juno': 'juno-network',
  'dydx': 'dydx',
  'saga': 'saga-2',
  'omniflixhub': 'omniflix-network',
  'stargaze': 'stargaze',
  'stride': 'stride',
  'sentinel': 'sentinel',
  'archway': 'archway',
  'noble': 'noble',
  'persistence': 'persistence',
  'evmos': 'evmos',
  'injective': 'injective-protocol',
  'secret': 'secret',
  'terra': 'terra-luna-2',
  'kujira': 'kujira'
} as const;